### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [volodinroman/FlowBased_Programming_Py#2]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by volodinroman** [comment]
> Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

Hey, no license, just use it the way you want

**Comment by suprafun** [comment]
Thank you so very much. Would it be possible for you to please upload a formal license (e.g. MIT, BSD, GPL, whatever you prefer) to the repo. ? I ask because it would be helpful for others, so that they can be clear on if and how they could learn or use this project. Thank you.

**Comment by volodinroman** [comment]
Done !
